// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.ClubType;
import com.team13.club.domain.ClubTypeDataOnDemand;
import com.team13.club.domain.ClubTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClubTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClubTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClubTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClubTypeIntegrationTest: @Transactional;
    
    @Autowired
    ClubTypeDataOnDemand ClubTypeIntegrationTest.dod;
    
    @Test
    public void ClubTypeIntegrationTest.testCountClubTypes() {
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", dod.getRandomClubType());
        long count = ClubType.countClubTypes();
        Assert.assertTrue("Counter for 'ClubType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClubTypeIntegrationTest.testFindClubType() {
        ClubType obj = dod.getRandomClubType();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to provide an identifier", id);
        obj = ClubType.findClubType(id);
        Assert.assertNotNull("Find method for 'ClubType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClubType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClubTypeIntegrationTest.testFindAllClubTypes() {
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", dod.getRandomClubType());
        long count = ClubType.countClubTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClubType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClubType> result = ClubType.findAllClubTypes();
        Assert.assertNotNull("Find all method for 'ClubType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClubType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClubTypeIntegrationTest.testFindClubTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", dod.getRandomClubType());
        long count = ClubType.countClubTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClubType> result = ClubType.findClubTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClubType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClubType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClubTypeIntegrationTest.testFlush() {
        ClubType obj = dod.getRandomClubType();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to provide an identifier", id);
        obj = ClubType.findClubType(id);
        Assert.assertNotNull("Find method for 'ClubType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClubType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ClubType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClubTypeIntegrationTest.testMergeUpdate() {
        ClubType obj = dod.getRandomClubType();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to provide an identifier", id);
        obj = ClubType.findClubType(id);
        boolean modified =  dod.modifyClubType(obj);
        Integer currentVersion = obj.getVersion();
        ClubType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClubType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClubTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", dod.getRandomClubType());
        ClubType obj = dod.getNewTransientClubType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClubType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClubType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ClubType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClubTypeIntegrationTest.testRemove() {
        ClubType obj = dod.getRandomClubType();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClubType' failed to provide an identifier", id);
        obj = ClubType.findClubType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ClubType' with identifier '" + id + "'", ClubType.findClubType(id));
    }
    
}
