// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.ClubType;
import com.team13.club.domain.ClubTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ClubTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClubTypeDataOnDemand: @Component;
    
    private Random ClubTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ClubType> ClubTypeDataOnDemand.data;
    
    public ClubType ClubTypeDataOnDemand.getNewTransientClubType(int index) {
        ClubType obj = new ClubType();
        setNametype(obj, index);
        return obj;
    }
    
    public void ClubTypeDataOnDemand.setNametype(ClubType obj, int index) {
        String nametype = "nametype_" + index;
        obj.setNametype(nametype);
    }
    
    public ClubType ClubTypeDataOnDemand.getSpecificClubType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ClubType obj = data.get(index);
        Long id = obj.getId();
        return ClubType.findClubType(id);
    }
    
    public ClubType ClubTypeDataOnDemand.getRandomClubType() {
        init();
        ClubType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ClubType.findClubType(id);
    }
    
    public boolean ClubTypeDataOnDemand.modifyClubType(ClubType obj) {
        return false;
    }
    
    public void ClubTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ClubType.findClubTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ClubType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ClubType>();
        for (int i = 0; i < 10; i++) {
            ClubType obj = getNewTransientClubType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
