// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.Club;
import com.team13.club.domain.ClubDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ClubDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClubDataOnDemand: @Component;
    
    private Random ClubDataOnDemand.rnd = new SecureRandom();
    
    private List<Club> ClubDataOnDemand.data;
    
    public Club ClubDataOnDemand.getNewTransientClub(int index) {
        Club obj = new Club();
        setClubname(obj, index);
        return obj;
    }
    
    public void ClubDataOnDemand.setClubname(Club obj, int index) {
        String clubname = "clubname_" + index;
        obj.setClubname(clubname);
    }
    
    public Club ClubDataOnDemand.getSpecificClub(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Club obj = data.get(index);
        Long id = obj.getId();
        return Club.findClub(id);
    }
    
    public Club ClubDataOnDemand.getRandomClub() {
        init();
        Club obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Club.findClub(id);
    }
    
    public boolean ClubDataOnDemand.modifyClub(Club obj) {
        return false;
    }
    
    public void ClubDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Club.findClubEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Club' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Club>();
        for (int i = 0; i < 10; i++) {
            Club obj = getNewTransientClub(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
