// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.ClubType;

privileged aspect ClubType_Roo_JavaBean {
    
    public String ClubType.getNametype() {
        return this.nametype;
    }
    
    public void ClubType.setNametype(String nametype) {
        this.nametype = nametype;
    }
    
}
