// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.Club;

privileged aspect Club_Roo_JavaBean {
    
    public String Club.getClubname() {
        return this.clubname;
    }
    
    public void Club.setClubname(String clubname) {
        this.clubname = clubname;
    }
    
}
