// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.Equiment;

privileged aspect Equiment_Roo_JavaBean {
    
    public String Equiment.getName() {
        return this.name;
    }
    
    public void Equiment.setName(String name) {
        this.name = name;
    }
    
}
