// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.EquipmentList;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EquipmentList_Roo_Configurable {
    
    declare @type: EquipmentList: @Configurable;
    
}
