// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.team13.club.domain;

import com.team13.club.domain.Major;

privileged aspect Major_Roo_JavaBean {
    
    public String Major.getMajors() {
        return this.Majors;
    }
    
    public void Major.setMajors(String Majors) {
        this.Majors = Majors;
    }
    
}
